age_keys:
  # Host keys
  - &muncher age10pkhfq9cq57yucgk2wlzvp4tn0ld593yeegrprrx7ttqfsk5ucqqgkue42
  - &scruncher age1fwhcuc4u7n3huw0hagee2ahvzm4fcxr7cj043326ckgmqphxds4qzj64av
  # master encryption key
  - &master age1xvyp63kuszp4u0ke4lf84wstgt6td04v6w605twh3mwqaedv9u8sdm8g4j
creation_rules:
  - path_regex: (^|/)(muncher/secrets|secrets/muncher)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *muncher
        - *master
  - path_regex: (^|/)(scruncher/secrets|secrets/scruncher)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *scruncher
        - *master
